### ISSUE TITLE
Traveler can reserve from a couch listing show view

### ISSUE THREAD

**Issue by tmikeschu** [tmikeschu/air_bnb_clone#34]
As a traveler
when I visit the page for a couch listing
and I select reservation dates
and I click 'Reserve'
then I am taken to my traveler reservations page
and I see a link to that listing.

**Comment by ski-climb** [comment]
One thought for how a user might end up on this page is after searching for a larger (e.g. 2 week) date range from the home page, then after arriving on the couches index, clicking through here to a couch show which might show the dates which that couch is available.  Looking at the story above, it looks as though you guys did a nice job of considering this already.  But I just spoke with Schutte and wanted to record our observations.
